Repository yfosp/main-website, pull requests merged in 2023-10, with the labels that each got.

#118 Fix documentation
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#119 Add dollarboysushil as new contributor
  CONTRIBUTORS.md
  community-website/pages/contributors.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#125 Add Web Development Resources into the community website
  CONTRIBUTORS.md
  community-website/pages/contributors.tsx
  community-website/pages/educational-resources.tsx
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#127 Add other resources - i.e. links to developer roadmaps
  community-website/pages/educational-resources.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#128 Fix member count
  community-website/pages/index.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#129 Add new members as of 04/10/2023
  community-website/pages/community-members.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#130 Bug fix - fix incorrect image URL
  community-website/pages/community-members.tsx
Labels: bug, hacktoberfest, hacktoberfest-accepted
